# environment.yml

#DeepLabCut2.0 Toolbox (deeplabcut.org)
#© A. & M.W. Mathis Labs
#https://github.com/DeepLabCut/DeepLabCut
#Please see AUTHORS for contributors.

#https://github.com/DeepLabCut/DeepLabCut/blob/master/AUTHORS
#Licensed under GNU Lesser General Public License v3.0
#
# DeepLabCut environment
# FIRST: INSTALL CORRECT DRIVER for GPU, see https://stackoverflow.com/questions/30820513/what-is-the-correct-version-of-cuda-for-my-nvidia-driver/30820690
#
# AFTER THIS FILE IS INSTALLED, if you have a GPU be sure to install `conda forge cudnn`
#
# install: conda env create -f environment.yml
#          conda env create --file https://raw.githubusercontent.com/bbo-lab/DeepLabCut/mpinb/environment.yml
# update:  conda env update -f environment.yml
#
# after activation of the environment, run conda-environments/postinst.sh
#
name: dlc2mpinb
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - pip
  - ipython
  - jupyter
  - nb_conda
  - notebook<7.0.0
  - ffmpeg
  - cuda<12.0.0
  - cuda-version<12.0.0
  - cuda-compiler<12.0.0
  - cuda-runtime<12.0.0
  - cuda-toolkit<12.0.0
  - cuda-cudart<12.0.0
  - cuda-libraries<12.0.0
  - cuda-nvcc<12.0.0
  - cuda-tools<12.0.0
  - cuda-cccl<12.0.0
  - numpy<2.0.0
  - pip:
    - "deeplabcut[gui,tf]@git+https://github.com/bbo-lab/DeepLabCut.git@mpinb"
